services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: mercuri_user
      POSTGRES_PASSWORD: mercuri_pass
      POSTGRES_DB: mercuri_db
      LANG: en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mercuri_user -d mercuri_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:alpine3.22
    container_name: mercuri_cache
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
