spring:
  application:
    name: "Mercuri"
  datasource:
    url: jdbc:postgresql://localhost:5432/mercuri_db
    username: mercuri_user
    password: mercuri_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: "Mercuri_Hikari_Pool"
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format-sql: true

jwt:
  secret-key: ${JWT_SECRET_BASE64}
  access-token-expiration: 900000 # in milliseconds (15 minutes = 900,000ms)
  refresh-token-expiration: 604800000 # in milliseconds (7 days = 604,800,000ms)
