[versions]
# Kotlin and Gradle
kotlin = "2.2.20"

# Quality
detekt = "2.0.0-alpha.1"
spotless = "8.1.0"
ktlint = "1.7.1"

# Spring Boot
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"

# Observability
kotlin-logging = "7.0.13"

# Testing
kotest = "6.0.7"
mockito-kotlin = "6.1.0"
kover = "0.9.4"

# Security
jjwt = "0.13.0"

[libraries]
# Kotlin
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }

# Testing
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

# Security
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }

# Spring Boot
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

# Quality
detekt = { id = "dev.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

# Testing
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
